# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            mipearson
tagline:          ''
description:      ''
url:              http://mipearson.id.au

author:
  name:           'Michael Pearson'
  url:            https://twitter.com/mipearson

paginate:         5
